import './styles/main.css'

import './component/App-Bar.js'
import './component/Footer-App.js'
import './component/Loading-Indicator'
import './component/Note-Form.js'
import './component/Notes-App.js'
import './component/Notes-Card.js'
import './component/Notes-List.js'
import './component/Home-Hero.js'
import './utils/darkMode.js'